### ISSUE TITLE
Metadata generator should support multiple paths to jars, and generate metadata for them.

### ISSUE THREAD

**Issue by Plamen5kov** [NativeScript/android-metadata-generator#12]
Problem:
Currently the metadata-generator can only use path to directory with jars to generate metadata.
This creates the need for all necessary jars to be copied in one directory (which can create additional problems if only some of the jars need to be included or some jars should be deleted at build time).

Suggestion:
A more elegant solution will be for the metadata-generator to accept as input parameters, paths to all jars.

**Comment by Plamen5kov** [comment]
7feea9c06033bfaea5a5f0a0d0dddf821496316f

**Comment by slavchev** [comment]
Done with https://github.com/NativeScript/android-metadata-generator/pull/13
